# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 4, size: 0.6925, name: raw_base_tag},
    {id: 580, size: 0.044, name: raw_gripper_tag}, 
    {id: 586, size: 0.044, name: raw_tool_tag},
    {id: 585, size: 0.044, name: raw_tag_tag},
    {id: 50, size: 0.080, name: raw_quiver_tag}
  ]

# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    # {
    #   name: 'base_bundle',
    #   layout:
    #     [
    #       # {id: 4, size: 0.06925, x: 0.119725, y: 0.119725, z: -0.0102, qw: 1, qx: 0, qy: 0, qz: 0},
    #       # {id: 4, size: 0.06925, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #     ]
    # },
  ]
